title: Zbalermorna
description: A diacritic orthography for Lojban
baseurl: ""
github_username: jackhumbert
repository: jackhumbert/zbalermorna
gems:
  - jekyll-redirect-from
exclude: [ 'ime/windows/zlm' ]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"